pipeline {
    agent any

    // stages {
    //     stage('Clone Repository') {
    //         steps {
    //             git 'https://github.com/Srinu7780/backend_springboot.git'
    //         }
    //     }

    //     stage('Build') {
    //         steps {
    //             sh 'mvn clean package'
    //         }
    //     }

    //     stage('Test') {
    //         steps {
    //             sh 'mvn test'
    //         }
    //     }

        stage('Deploy') {
            steps {
                echo "Deployment steps go here"
            }
        }
    }
}
